--CREATE USER PITAPET IDENTIFIED BY "PITAPET";
--GRANT RESOURCE, CONNECT, DBA TO PITAPET;

-------------------------------------------------
CREATE TABLE MEMBER (
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
    NAME VARCHAR2(15) NOT NULL,
    NICKNAME VARCHAR2(15) NOT NULL,
    PHONE VARCHAR2(13),
    EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(100),
    PET VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);
-- DROP TABLE MEMBER;

COMMENT ON COLUMN MEMBER.NO IS '회원번호';
COMMENT ON COLUMN MEMBER.ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.PASSWORD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.ROLE IS '회원타입';
COMMENT ON COLUMN MEMBER.NAME IS '회원명';
COMMENT ON COLUMN MEMBER.NICKNAME IS '회원닉네임';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.PET IS '애완동물';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';

CREATE SEQUENCE SEQ_UNO;

INSERT INTO MEMBER (
    NO, 
    ID, 
    PASSWORD, 
    ROLE,
    NAME, 
    NICKNAME,
    PHONE, 
    EMAIL, 
    ADDRESS, 
    PET, 
    STATUS, 
    ENROLL_DATE, 
    MODIFY_DATE
) VALUES(
    SEQ_UNO.NEXTVAL, 
    'eaaha', 
    '1234', 
    'USER', 
    '사용자', 
    'ㄴㅇㅅ',
    '010-4179-4341', 
    'admin@iei.or.kr', 
    '서울시 강남구 역삼동',
    NULL,
    DEFAULT,
    DEFAULT,
    DEFAULT
);

-------------------------------------------------
-------------------- PRODUCT --------------------
CREATE TABLE PRODUCT (
    NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(1000),
    PRICE NUMBER,
    ORIGINAL_FILENAME VARCHAR2(100), 
	RENAMED_FILENAME VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATED_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);
--DROP TABLE PRODUCT;

CREATE SEQUENCE SEQ_PRODUCT_NO;
--DROP SEQUENCE SEQ_PRODUCT_NO;

COMMENT ON COLUMN PRODUCT.NO IS '상품번호';
COMMENT ON COLUMN PRODUCT.TITLE IS '상품명';
COMMENT ON COLUMN PRODUCT.CONTENT IS '상품설명';
COMMENT ON COLUMN PRODUCT.PRICE IS '가격(단위:원)';
COMMENT ON COLUMN PRODUCT.ORIGINAL_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN PRODUCT.RENAMED_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN PRODUCT.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN PRODUCT.CREATE_DATE IS '작성일';
COMMENT ON COLUMN PRODUCT.MODIFY_DATE IS '수정일';

INSERT INTO PRODUCT VALUES(SEQ_PRODUCT_NO.NEXTVAL, '그립톡', '핸드폰에 부착할 수 있는 그립톡입니다.', 10000, NULL, NULL, 'Y', DEFAULT, DEFAULT);


------------------------------------------------------
-------------------- PRODUCT_SELL --------------------
CREATE TABLE SELL (
    NO NUMBER PRIMARY KEY,
    COUNT NUMBER,
    MEMBER_NO NUMBER,
    PRODUCT_NO NUMBER,
    CONSTRAINT FK_SELL_MEMBER FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO) ON DELETE SET NULL,
    CONSTRAINT FK_SELL_PRODUCT FOREIGN KEY(PRODUCT_NO) REFERENCES PRODUCT(NO) ON DELETE SET NULL
);
--DROP TABLE SELL

CREATE SEQUENCE SEQ_SELL_NO;

COMMENT ON COLUMN SELL.NO IS '주문번호';
COMMENT ON COLUMN SELL.COUNT IS '주문수량';
COMMENT ON COLUMN SELL.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN SELL.PRODUCT_NO IS '상품번호';

INSERT INTO SELL VALUES(SEQ_SELL_NO.NEXTVAL, 2, 1, 1);

SELECT S.NO, M.NO AS MEMBER_NO, P.TITLE, P.PRICE, S.COUNT
FROM SELL S
JOIN MEMBER M ON (S.MEMBER_NO = M.NO)
JOIN PRODUCT P ON (S.PRODUCT_NO = P.NO);

